packages:
  - apps/*
  - lib/*

catalog:
  '@sentry/nextjs': ^10.26.0
  '@types/node': ^22.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  next: ^15.5.9
  react: ^18.3.0
  react-dom: ^18.3.0
  recharts: ^2.15.4
  tailwindcss: 3.4.1
  tsx: 4.20.3
  typescript: ~5.9.0
  valtio: ^1.12.0
  zod: ^3.25.76

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - contentlayer2
  - core-js
  - es5-ext
  - esbuild
  - libpg-query
  - msw
  - node-pty
  - protobufjs
  - sharp

overrides:
  '@eslint/eslintrc>js-yaml': ^4.1.1
  esbuild: ^0.25.2
  nodemailer: ^7.0.11
  refractor>prismjs: ^1.30.0
  tar: ^7.0.0
  tmp: ^0.2.4
