import type { Scenario } from './types'

export const scenarios: Scenario[] = [
  {
    id: 'kubectl-delete',
    agentName: 'k8s-deployer',
    agentIcon: 'terminal',
    toolCall: 'kubectl delete pod api-server-7d4f',
    toolName: 'Kubernetes',
    toolIcon: 'kubernetes',
    environment: 'production',
    decision: 'APPROVAL_REQUIRED',
    policyRule: 'require-approval-destructive-prod',
    slackApproval: {
      channel: '#prod-approvals',
      requestedBy: 'k8s-deployer',
      approvedBy: 'Sarah Chen',
      approverAvatar: 'SC',
      message: 'k8s-deployer wants to delete pod api-server-7d4f in production',
    },
    receipt: { traceId: 'tr_8x2k4m9n', hmac: 'sha256:7f3a...e91d' },
  },
  {
    id: 's3-delete',
    agentName: 'cleanup-agent',
    agentIcon: 'cloud',
    toolCall: 's3:DeleteBucket logs-2024-archive',
    toolName: 'AWS S3',
    toolIcon: 'aws-s3',
    environment: 'production',
    decision: 'BLOCKED',
    policyRule: 'block-destructive-s3-prod',
    receipt: { traceId: 'tr_3j7m2p5q', hmac: 'sha256:2b4c...f8a3' },
  },
  {
    id: 'github-merge',
    agentName: 'ci-bot',
    agentIcon: 'git',
    toolCall: 'github:merge-pr #1482 → main',
    toolName: 'GitHub',
    toolIcon: 'github',
    environment: 'production',
    decision: 'ALLOWED',
    policyRule: 'allow-ci-merge-with-approval',
    receipt: { traceId: 'tr_9d1f4h6k', hmac: 'sha256:c5e7...3d2a' },
  },
  {
    id: 'stripe-refund',
    agentName: 'support-agent',
    agentIcon: 'credit-card',
    toolCall: 'stripe:refund $4,200 → cus_L4x9mK',
    toolName: 'Stripe',
    toolIcon: 'stripe',
    environment: 'production',
    decision: 'APPROVAL_REQUIRED',
    policyRule: 'review-refunds-over-1000',
    slackApproval: {
      channel: '#finance-approvals',
      requestedBy: 'support-agent',
      approvedBy: 'Mike Torres',
      approverAvatar: 'MT',
      message: 'support-agent wants to refund $4,200 to cus_L4x9mK',
    },
    receipt: { traceId: 'tr_5g8j1m3p', hmac: 'sha256:1a9b...7c4e' },
  },
]
